### PR TITLE
Improve hamburger burger design

### LINKED ISSUE #96: [BUG] Improve Hamburger Menu design
## Description
The hamburger menu design can be improved to match designs by doing the tasks below.

## Screenshots
screen shot 2018-10-11 at 16 05 45

## Tasks

- [ ] 1. Logo should be above the modal
- [ ] 2.1. Right align menu items
- [ ] 2.2. Update font style + size
- [ ] 2.3. Menu items should be as in design
- [ ] 3. Close button should be above modal and menu items right aligned to it

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

This PR has
- moved Logo position above the modal
- right aligned menu items
-  updated font style + size
- changed menu items list as per design
- adjusted & move Close button above the modal and aligned menu items right to it

Fixes #96 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
screenshot from 2018-10-24 14-22-54

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
I see we've new items like *Stories* @DavidLemayian, should these be going anywhere or should we hide them for the `alpha` milestone?

cc @KhadijaMahanga

**Comment by DavidLemayian** [comment]
@kilemensi What stories? Maybe that's for HURUmap Land?

**Comment by kilemensi** [comment]
On the Hamburger Menu there are new items: *STORIES*, *RESOURCES*, *DATA*, etc. @DavidLemayian

**Comment by DavidLemayian** [comment]
Stories should point to Medium articles, Resources to the assembly page, Data to the archive.

**Pull request merged**
