### PR TITLE
Fix/sensorapidata

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

Gauge value pulling  from api (http://api.airquality.codeforafrica.org/v1/new) Sensors values that are update after every 5 minutes

Fixes # 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshots

screenshot from 2018-10-17 10-46-35

screenshot from 2018-10-17 10-46-19

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
I've reorganize the fetch/processing of the data @KhadijaMahanga. Please recheck.

**Comment by KhadijaMahanga** [comment]
I have reviewed the changes @kilemensi , good and ready for merge

**Comment by KhadijaMahanga** [comment]
I have reviewed the changes @kilemensi , good and ready for merge

**Comment by KhadijaMahanga** [comment]
I have reviewed the changes @kilemensi Ready to merge

**Pull request closed without merging**
