### PR TITLE
Fix dial component in the city page

### PR DESCRIPTION
**Pull request by nerdlet**
## Description
Fixes # 161644232

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

### Improved

screenshot_2019-03-06 sensors africa air city 3

### Current

screenshot_2019-03-06 sensors africa air city 2

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by nerdlet** [comment]
@kilemensi Fixed it

**Comment by kilemensi** [comment]
Not yet @nerdlet 

screenshot from 2019-03-06 16-36-22

You can test it by setting `40` in the `RadialGauge.render` method like below:
```javascript
  render() {
    const { classes, percentageRelative, isOverGuideline } = this.props;
    let { airPollMeasurement } = { airPollMeasurement: 40 };
```

**Comment by nerdlet** [comment]
@kilemensi I was able to fix it but had to change `isNan` to `Number.isNaN` to comply with the eslint rules. This is what am getting...plus the needle is starting from `40` instead of `0`

image

**Comment by kilemensi** [comment]
Push your changes @nerdlet so that I can see why it starts at `40`

**Comment by nerdlet** [comment]
@kilemensi Already done

**Comment by kilemensi** [comment]
> @kilemensi Already done

Seems to work fine @nerdlet 

screenshot from 2019-03-06 18-47-05

Just a few margin/alignment issues on the value there and we'll be done.

screenshot from 2019-03-06 18-45-47

**Pull request merged**
