### PR TITLE
Update content for the story showcase component

### PR DESCRIPTION
**Pull request by nerdlet**
## Description
Fixes #162660790

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by nerdlet** [comment]
@kilemensi Working on it

**Comment by nerdlet** [comment]
@kilemensi Push the latest changes. Could you test it on your end?

**Comment by kilemensi** [comment]
> @kilemensi Push the latest changes. Could you test it on your end?

What changes @nerdlet? I don't see any commits.

**Comment by nerdlet** [comment]
@kilemensi Sorry about that. Also made changes the wrong branch. You should see the changes right now

**Comment by kilemensi** [comment]
> @kilemensi Sorry about that. Also made changes the wrong branch. You should see the changes right now

You've missed one link @nerdlet : `http://www.designindaba.com/articles/creative-work/buggyair-mobile-air-pollution-tracker`

**Comment by nerdlet** [comment]
@kilemensi Done

**Comment by kilemensi** [comment]
Works @nerdlet.

But are we sorting the stories based on date with most recent first? I see a couple of stories from 2014 and 2015 between stories from 2016. Either dates are messed up or the sorting is wrong.

screenshot from 2018-12-14 16-02-22

screenshot from 2018-12-14 16-02-57

There is even on from **2019**!

screenshot from 2018-12-14 16-03-16

**Comment by nerdlet** [comment]
@kilemensi The stories we have date back to 2014. Maybe to make it user-friendly, we should sort it out. Keep in mind that these stories are just but a handful of other stories in the Google sheet we have.

**Comment by nerdlet** [comment]
@kilemensi Removed most of the stories, so we have six at the moment.

**Pull request merged**
