### PR TITLE
Fix content layout on the data page

### PR DESCRIPTION
**Pull request by nerdlet**
## Description
Fixes #163421579

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Current:

image

#### Medium & large screens

screenshot_2019-01-25 sensors africa air data

#### Small screens

screenshot_2019-01-25 sensors africa air data 1

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Before I review, can you explain the problem to me @nerdlet? The site seems fine to me.

screenshot_2019-01-23 sensors africa air data

**Comment by nerdlet** [comment]
@kilemensi Attached the current design in the PR. The content and div should be center of the page instead its veered so much to the left

**Comment by kilemensi** [comment]
> @kilemensi Attached the current design in the PR. The content and div should be center of the page instead its veered so much to the left

But that is by design @nerdlet. It maintains the vertical rhythm i.e. all components have the same width. If we really see it as a problem then why don't we try a two column layout with each column having the same width as the indoor/outdoor pollution components? That way we'll be able to maintain the width and yet bring the text close together.

**Comment by nerdlet** [comment]
@kilemensi Okay. Then let's leave it as is. I am not of the idea of having a two column layout...the information works best as text to be read, like an article

**Comment by kilemensi** [comment]
This is what I had in mind @nerdlet.

screenshot_2019-01-25 sensors africa air data

The width of data content is similar to the width of support content, footer content, etc.

**Pull request merged**
